



ALTER TABLE DB_REFERENTIEL_DEV.S_REFERENTIEL.T_F_EVENEMENT ADD COLUMN FERMETURE_GLOBALE_PISTES BOOLEAN DEFAULT FALSE ; 


CREATE TABLE IF NOT EXISTS DB_REFERENTIEL_DEV.S_REFERENTIEL.T_R_CONTACT_INTERNE (
    CODE_CONTACT NUMBER AUTOINCREMENT PRIMARY KEY,
    NOM VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    SERVICE VARCHAR(100),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    DATE_CREATION TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) ; 