
-------------------------------------------------------------------
----- TABLE_NAME UTILISEE PAR L'APPLICATION GESTION PARC
-------------------------------------------------------------------
-- SCRIPT DE RENOMMAGE DES TABLES ----

USE DATABASE DB_REFERENTIEL_DEV ;

USE ROLE R_DATA_ING_DEV ;

ALTER TABLE S_REFERENTIEL.T_BASE_PARC_COMMERCIAL 		RENAME TO 	S_REFERENTIEL.T_R_PARC_COMMERCIAL; 
ALTER TABLE S_REFERENTIEL.T_BASE_PARC_COMMERCIAL 		RENAME TO 	S_REFERENTIEL.T_R_PARC_COMMERCIAL;
ALTER TABLE S_REFERENTIEL.T_DISTRICT 					RENAME TO 	S_REFERENTIEL.T_R_DISTRICT;        
ALTER TABLE S_REFERENTIEL.T_FLAG 						RENAME TO 	S_REFERENTIEL.T_R_FLAG;
ALTER TABLE S_REFERENTIEL.T_GESTION 					RENAME TO 	S_REFERENTIEL.T_R_GESTION;
ALTER TABLE S_REFERENTIEL.T_NATURE_JURIDIQUE 			RENAME TO 	S_REFERENTIEL.T_R_NATURE_JURIDIQUE;
ALTER TABLE S_REFERENTIEL.T_BASE_PARC  					RENAME TO 	S_REFERENTIEL.T_R_PARC;
ALTER TABLE S_REFERENTIEL.T_BASE_PARC_DIVERS 			RENAME TO 	S_REFERENTIEL.T_R_PARC_DIVERS;
ALTER TABLE S_REFERENTIEL.T_BASE_PARC_EXPLOITATION  	RENAME TO 	S_REFERENTIEL.T_R_PARC_EXPLOITATION;
ALTER TABLE S_REFERENTIEL.T_BASE_PARC_JURIDIQUE 		RENAME TO 	S_REFERENTIEL.T_R_PARC_JURIDIQUE;
ALTER TABLE S_REFERENTIEL.T_BASE_PARC_SECURITE_INCENDIE RENAME TO 	S_REFERENTIEL.T_R_PARC_SECURITE_INCENDIE;
ALTER TABLE S_REFERENTIEL.T_PEAGEUR 					RENAME TO 	S_REFERENTIEL.T_R_PEAGEUR;
ALTER TABLE S_REFERENTIEL.T_SECTEUR 					RENAME TO 	S_REFERENTIEL.T_R_SECTEUR;
ALTER TABLE S_REFERENTIEL.T_TYPE_PARC 					RENAME TO 	S_REFERENTIEL.T_R_TYPE_PARC;
ALTER TABLE S_REFERENTIEL.T_VILLE 						RENAME TO 	S_REFERENTIEL.T_R_VILLE;


-------------------------------------------------------------------
-------------------------------------------------------------------
----- TABLE_NAME UTILISEE PAR L'APPLICATION GESTION EVENEMENT
-------------------------------------------------------------------
-------------------------------------------------------------------
-----  TABLE_NAME  T_F_HISTORIQUE_EVENEMENT
-------------------------------------------------------------------

CREATE OR REPLACE TABLE DB_REFERENTIEL_DEV.S_REFERENTIEL.T_F_HISTORIQUE_EVENEMENT (
	CODE_HISTORIQUE NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
	CODE_EVENEMENT NUMBER(38,0) NOT NULL,
	TITRE_EVENEMENT VARCHAR(300),
	TYPE_EVENEMENT VARCHAR(200),
	CATEGORIE VARCHAR(200),
	DESCRIPTION VARCHAR(500),
	LIEU VARCHAR(200),
	VILLE VARCHAR(200),
	IMPACT VARCHAR(200),
	NIVEAU_SEVERITE NUMBER(38,0),
	DATE_DEBUT TIMESTAMP_NTZ(9),
	DATE_FIN TIMESTAMP_NTZ(9),
	IS_JOURNEE_PARTIELLE BOOLEAN,
	CRENEAU VARCHAR(20),
	NB_PLACES_IMPACTEES NUMBER(38,0),
	FERMETURE_TOTALE BOOLEAN,
	NB_PISTES_ENTREE_FERMEES NUMBER(38,0),
	NB_PISTES_SORTIE_FERMEES NUMBER(38,0),
	TYPE_TRAVAUX VARCHAR(20),
	CONTACT_INTERNE VARCHAR(200),
	CONTACT_EXTERNE VARCHAR(200),
	IS_TRAVAUX_PHASES BOOLEAN,
	COMMENTAIRE VARCHAR(2000),
	PARKINGS_IMPACTES VARCHAR(2000),
	IS_ACTIVE NUMBER(1,0) DEFAULT 1,
	MODIFIE_PAR VARCHAR(100),
	ACTION VARCHAR(50),
	DATE_DEBUT_VALIDITE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	DATE_FIN_VALIDITE TIMESTAMP_NTZ(9),
	PRIMARY KEY (CODE_HISTORIQUE)
);

-------------------------------------------------------------------
-----  TABLE_NAME  T_R_TYPE_EVENEMENT
-------------------------------------------------------------------


CREATE OR REPLACE TABLE DB_REFERENTIEL_DEV.S_REFERENTIEL.T_R_TYPE_EVENEMENT (
	CODE_TYPE_EVENEMENT NUMBER(38,0) NOT NULL,
	LIBELLE_TYPE_EVENEMENT VARCHAR(200) NOT NULL,
	CATEGORIE VARCHAR(100) NOT NULL,
	IS_TRAVAUX BOOLEAN DEFAULT FALSE,
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	PRIMARY KEY (CODE_TYPE_EVENEMENT)
);

-------------------------------------------------------------------
-----  TABLE_NAME  T_R_DESCRIPTION_EVENEMENT
-------------------------------------------------------------------



CREATE OR REPLACE TABLE DB_REFERENTIEL_DEV.S_REFERENTIEL.T_R_DESCRIPTION_EVENEMENT (
	CODE_DESCRIPTION NUMBER(38,0) NOT NULL,
	CODE_TYPE_EVENEMENT NUMBER(38,0) NOT NULL,
	LIBELLE_DESCRIPTION VARCHAR(300) NOT NULL,
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	PRIMARY KEY (CODE_DESCRIPTION)
);


-------------------------------------------------------------------
-----  TABLE_NAME  T_R_IMPACT_EVENEMENT
-------------------------------------------------------------------

CREATE OR REPLACE TABLE DB_REFERENTIEL_DEV.S_REFERENTIEL.T_R_IMPACT_EVENEMENT (
	CODE_IMPACT NUMBER(38,0) NOT NULL,
	LIBELLE_IMPACT VARCHAR(200) NOT NULL,
	NIVEAU_SEVERITE NUMBER(1,0),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	PRIMARY KEY (CODE_IMPACT)
);


-------------------------------------------------------------------
-----  TABLE_NAME  T_F_EVENEMENT_PARC
-------------------------------------------------------------------

CREATE OR REPLACE TABLE DB_REFERENTIEL_DEV.S_REFERENTIEL.T_F_EVENEMENT_PARC (
	CODE_EVENEMENT NUMBER(38,0) NOT NULL,
	CODE_PARC VARCHAR(20) NOT NULL,
	NOM_PARC VARCHAR(200)
);

-------------------------------------------------------------------
-----  TABLE_NAME  T_R_LIEU_EVENEMENT
-------------------------------------------------------------------

CREATE OR REPLACE TABLE DB_REFERENTIEL_DEV.S_REFERENTIEL.T_R_LIEU_EVENEMENT (
	CODE_LIEU NUMBER(38,0) NOT NULL,
	LIBELLE_LIEU VARCHAR(300) NOT NULL,
	VILLE VARCHAR(100),
	CODE_POSTAL VARCHAR(10),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	PRIMARY KEY (CODE_LIEU)
);

-------------------------------------------------------------------
-----  TABLE_NAME  T_F_EVENEMENT
-------------------------------------------------------------------

CREATE OR REPLACE TABLE DB_REFERENTIEL_DEV.S_REFERENTIEL.T_F_EVENEMENT (
	CODE_EVENEMENT NUMBER(38,0) NOT NULL,
	TITRE_EVENEMENT VARCHAR(300) NOT NULL,
	CODE_TYPE_EVENEMENT NUMBER(38,0) NOT NULL,
	CODE_DESCRIPTION NUMBER(38,0),
	DESCRIPTION_AUTRE VARCHAR(500),
	CODE_LIEU NUMBER(38,0),
	CODE_IMPACT NUMBER(38,0),
	DATE_DEBUT TIMESTAMP_NTZ(9) NOT NULL,
	DATE_FIN TIMESTAMP_NTZ(9),
	IS_JOURNEE_PARTIELLE BOOLEAN DEFAULT FALSE,
	CRENEAU VARCHAR(20),
	IS_PLACES_IMPACTEES BOOLEAN DEFAULT FALSE,
	NB_PLACES_IMPACTEES NUMBER(38,0),
	FERMETURE_TOTALE BOOLEAN DEFAULT FALSE,
	IS_PISTES_IMPACTEES BOOLEAN DEFAULT FALSE,
	NB_PISTES_ENTREE_FERMEES NUMBER(38,0),
	NB_PISTES_SORTIE_FERMEES NUMBER(38,0),
	TYPE_TRAVAUX VARCHAR(20),
	CONTACT_INTERNE VARCHAR(200),
	CONTACT_EXTERNE VARCHAR(200),
	IS_TRAVAUX_PHASES BOOLEAN DEFAULT FALSE,
	COMMENTAIRE VARCHAR(2000),
	NOM_CREATEUR VARCHAR(100),
	NOM_MODIFICATEUR VARCHAR(100),
	DATE_CREATION TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	DATE_MODIFICATION TIMESTAMP_NTZ(9),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	PRIMARY KEY (CODE_EVENEMENT)
);

-------------------------------------------------------------------
-----  TABLE_NAME  T_F_DISPONIBILITE_PARC
-------------------------------------------------------------------

CREATE OR REPLACE TABLE DB_REFERENTIEL_DEV.S_REFERENTIEL.T_F_DISPONIBILITE_PARC (
	CODE_PARC VARCHAR(10),
	NOM_PARC VARCHAR(100),
	CODE_EVENEMENT NUMBER(38,0),
	TITRE_EVENEMENT VARCHAR(500),
	TYPE_EVENEMENT VARCHAR(200),
	DATE_DEBUT TIMESTAMP_NTZ(9),
	DATE_FIN TIMESTAMP_NTZ(9),
	CAPACITE_EXPLOITEE NUMBER(38,0),
	NB_PLACES_IMPACTEES NUMBER(38,0),
	FERMETURE_TOTALE BOOLEAN,
	PLACES_DISPONIBLES NUMBER(38,0),
	TAUX_IMPACT FLOAT,
	IS_EN_COURS BOOLEAN,
	DATE_CALCUL TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-------------------------------------------------------------------
-----  TABLE_NAME  T_F_PHASE_TRAVAUX
-------------------------------------------------------------------

CREATE OR REPLACE TABLE DB_REFERENTIEL_DEV.S_REFERENTIEL.T_F_PHASE_TRAVAUX (
	CODE_PHASE NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
	CODE_EVENEMENT NUMBER(38,0) NOT NULL,
	NUMERO_PHASE NUMBER(38,0) NOT NULL,
	DATE_DEBUT TIMESTAMP_NTZ(9) NOT NULL,
	DATE_FIN TIMESTAMP_NTZ(9) NOT NULL,
	NB_PLACES_IMPACTEES NUMBER(38,0),
	COMMENTAIRE VARCHAR(1000),
	DATE_CREATION TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY (CODE_PHASE)
);

-------------------------------------------------------------------
-----  SCRIPT DE SUPPRESSION DES TABLE OBSELETES 
-------------------------------------------------------------------

DROP TABLE  S_REFERENTIEL.T_PARKING   ; 
DROP TABLE  S_REFERENTIEL.T_HISTORIQUE_EVENEMENT ; 
DROP TABLE  S_REFERENTIEL.T_TYPE_EVENEMENT ;
DROP TABLE  S_REFERENTIEL.T_IMPACT_EVENEMENT ; 
DROP TABLE  S_REFERENTIEL.T_EVENEMENT_PARC ; 
DROP TABLE  S_REFERENTIEL.T_LIEU_EVENEMENT; 
DROP TABLE  S_REFERENTIEL.T_BASE_EVENEMENT ;
 
 

 
 
 
 
 
 
 
 
 
