name: Streamlit Deploy PROD

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install PyJWT cryptography

      - name: Setup Snowflake key
        run: |
            mkdir -p /home/runner/.secrets

            printf "%s" "$SNOWFLAKE_PRIVATE_KEY_B64" | base64 --decode > /home/runner/.secrets/snowflake_key.p8
            chmod 600 /home/runner/.secrets/snowflake_key.p8

            printf "%s" "$SNOWFLAKE_PUBLIC_KEY" > /home/runner/.secrets/snowflake_key.pub
            chmod 600 /home/runner/.secrets/snowflake_key.pub
        env:
              SNOWFLAKE_PRIVATE_KEY_B64: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_B64 }}
              SNOWFLAKE_PRIVATE_KEY_PATH: /home/runner/.secrets/snowflake_key.p8
              SNOWFLAKE_PUBLIC_KEY: ${{ secrets.SNOWFLAKE_PUBLIC_KEY }}

      - name: Génération JWT
        run: |
            python - <<EOF >> $GITHUB_ENV
            import jwt, time
            from cryptography.hazmat.primitives import serialization

            import base64
            import hashlib

            public_key = serialization.load_pem_public_key(open("/home/runner/.secrets/snowflake_key.pub", "rb").read())
            private_key = open("/home/runner/.secrets/snowflake_key.p8", "rb").read()

            # Export DER
            public_key_der = public_key.public_bytes(
                encoding=serialization.Encoding.DER,
                format=serialization.PublicFormat.SubjectPublicKeyInfo
            )

            # SHA-256 hash
            sha256_hash = hashlib.sha256(public_key_der).digest()

            # Base64 encode
            fingerprint = base64.b64encode(sha256_hash).decode("utf-8")
            print({fingerprint})
            payload = {
                "iss": f"${{ secrets.SNOWFLAKE_ACCOUNT }}.${{ secrets.SNOWFLAKE_USER_PRD }}.SHA256:{fingerprint}",
                "sub": f"${{ secrets.SNOWFLAKE_ACCOUNT }}.${{ secrets.SNOWFLAKE_USER_PRD }}",
                "iat": int(time.time()),
                "exp": int(time.time()) + 60
            }

            token = jwt.encode(payload, private_key, algorithm="RS256")

            print(f"JWT={token}")
            EOF

      - name: Call Snowflake API (JWT)
        run: |
            curl -X POST "https://${{ secrets.SNOWFLAKE_ACCOUNT }}.snowflakecomputing.com/api/v2/statements" \
              -H "Authorization: Bearer $JWT" \
              -H "Content-Type: application/json" \
              -d '{
                "statement": "ALTER GIT REPOSITORY ${{ secrets.SNOWFLAKE_DATABASE_PRD }}.${{ secrets.SNOWFLAKE_SCHEMA }}.${{ secrets.SNOWFLAKE_GIT_PRD }} FETCH;",
                "warehouse": "${{ secrets.SNOWFLAKE_WAREHOUSE }}",
                "role": "${{ secrets.SNOWFLAKE_ROLE_PRD }}"
              }'

      - name: Actualisation des Streamlits
        run: |
          curl -s -X POST "https://${{ secrets.SNOWFLAKE_ACCOUNT }}.snowflakecomputing.com/api/v2/statements" \
            -H "Authorization: Bearer $JWT" \
            -H "Content-Type: application/json" \
            -d '{
              "statement":"SHOW TERSE STREAMLITS IN ${{ secrets.SNOWFLAKE_DATABASE_PRD }}.${{ secrets.SNOWFLAKE_SCHEMA }}"
              }' \
              > show.json

          jq -r '.data[] | @json' show.json | while read row; do

            NAME=$(echo $row | jq -r '.[1]')

            echo "Deploying "$NAME

            SQL=$(echo "ALTER STREAMLIT ${{ secrets.SNOWFLAKE_DATABASE_PRD }}.${{ secrets.SNOWFLAKE_SCHEMA }}.\"${NAME}\" ABORT")

            curl -X POST "https://${{ secrets.SNOWFLAKE_ACCOUNT }}.snowflakecomputing.com/api/v2/statements" \
                -H "Authorization: Bearer $JWT" \
                -H "Content-Type: application/json" \
                -d "$(jq -n --arg stmt "$SQL" '{statement: $stmt}')"

            SQL=$(echo "ALTER STREAMLIT ${{ secrets.SNOWFLAKE_DATABASE_PRD }}.${{ secrets.SNOWFLAKE_SCHEMA }}.\"${NAME}\" PULL")

            curl -X POST "https://${{ secrets.SNOWFLAKE_ACCOUNT }}.snowflakecomputing.com/api/v2/statements" \
                -H "Authorization: Bearer $JWT" \
                -H "Content-Type: application/json" \
                -d "$(jq -n --arg stmt "$SQL" '{statement: $stmt}')"
          done

